//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace JointMilitarySymbologyLibrary {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://disa.mil/JointMilSyML.xsd", IsNullable=false)]
    public partial class SymbolSet {
        
        private DoubleDigitType symbolSetCodeField;
        
        private LegacyLetterCodeType[] legacyCodingSchemeCodeField;
        
        private SymbolSetEntity[] entitiesField;
        
        private ModifiersTypeModifier[] sectorOneModifiersField;
        
        private ModifiersTypeModifier[] sectorTwoModifiersField;
        
        private SymbolSetLegacySymbol[] legacySymbolsField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string dimensionIDField;
        
        /// <remarks/>
        public DoubleDigitType SymbolSetCode {
            get {
                return this.symbolSetCodeField;
            }
            set {
                this.symbolSetCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegacyCodingSchemeCode")]
        public LegacyLetterCodeType[] LegacyCodingSchemeCode {
            get {
                return this.legacyCodingSchemeCodeField;
            }
            set {
                this.legacyCodingSchemeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Entity", IsNullable=false)]
        public SymbolSetEntity[] Entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Modifier", IsNullable=false)]
        public ModifiersTypeModifier[] SectorOneModifiers {
            get {
                return this.sectorOneModifiersField;
            }
            set {
                this.sectorOneModifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Modifier", IsNullable=false)]
        public ModifiersTypeModifier[] SectorTwoModifiers {
            get {
                return this.sectorTwoModifiersField;
            }
            set {
                this.sectorTwoModifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("LegacySymbol", IsNullable=false)]
        public SymbolSetLegacySymbol[] LegacySymbols {
            get {
                return this.legacySymbolsField;
            }
            set {
                this.legacySymbolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string DimensionID {
            get {
                return this.dimensionIDField;
            }
            set {
                this.dimensionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class DoubleDigitType {
        
        private ushort digitOneField;
        
        private ushort digitTwoField;
        
        private string[] textField;
        
        public DoubleDigitType() {
            this.digitOneField = ((ushort)(0));
            this.digitTwoField = ((ushort)(0));
        }
        
        /// <remarks/>
        public ushort DigitOne {
            get {
                return this.digitOneField;
            }
            set {
                this.digitOneField = value;
            }
        }
        
        /// <remarks/>
        public ushort DigitTwo {
            get {
                return this.digitTwoField;
            }
            set {
                this.digitTwoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LegacyFunctionCodeType {
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LegacyLetterCodeType {
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class SymbolSetEntity {
        
        private DoubleDigitType entityCodeField;
        
        private SymbolSetEntityEntityType[] entityTypesField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        private GeometryType geometryTypeField;
        
        public SymbolSetEntity() {
            this.geometryTypeField = GeometryType.POINT;
        }
        
        /// <remarks/>
        public DoubleDigitType EntityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EntityType", IsNullable=false)]
        public SymbolSetEntityEntityType[] EntityTypes {
            get {
                return this.entityTypesField;
            }
            set {
                this.entityTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CircleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CurveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DiamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string RectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string SquareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(GeometryType.POINT)]
        public GeometryType GeometryType {
            get {
                return this.geometryTypeField;
            }
            set {
                this.geometryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class SymbolSetEntityEntityType {
        
        private DoubleDigitType entityTypeCodeField;
        
        private SymbolSetEntityEntityTypeEntitySubType[] entitySubTypesField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public DoubleDigitType EntityTypeCode {
            get {
                return this.entityTypeCodeField;
            }
            set {
                this.entityTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EntitySubType", IsNullable=false)]
        public SymbolSetEntityEntityTypeEntitySubType[] EntitySubTypes {
            get {
                return this.entitySubTypesField;
            }
            set {
                this.entitySubTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CircleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CurveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DiamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string RectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string SquareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class SymbolSetEntityEntityTypeEntitySubType {
        
        private DoubleDigitType entitySubTypeCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public DoubleDigitType EntitySubTypeCode {
            get {
                return this.entitySubTypeCodeField;
            }
            set {
                this.entitySubTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CircleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CurveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DiamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string RectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string SquareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public enum GeometryType {
        
        /// <remarks/>
        POINT,
        
        /// <remarks/>
        LINE,
        
        /// <remarks/>
        AREA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class ModifiersTypeModifier {
        
        private DoubleDigitType modifierCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string categoryField;
        
        private string limitUseToField;
        
        /// <remarks/>
        public DoubleDigitType ModifierCode {
            get {
                return this.modifierCodeField;
            }
            set {
                this.modifierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string LimitUseTo {
            get {
                return this.limitUseToField;
            }
            set {
                this.limitUseToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class SymbolSetLegacySymbol {
        
        private LegacyFunctionCodeType[] legacyFunctionCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string entityIDField;
        
        private string entityTypeIDField;
        
        private string entitySubTypeIDField;
        
        private string modifierOneIDField;
        
        private string modifierTwoIDField;
        
        public SymbolSetLegacySymbol() {
            this.entityIDField = "NA";
            this.entityTypeIDField = "NA";
            this.entitySubTypeIDField = "NA";
            this.modifierOneIDField = "NA";
            this.modifierTwoIDField = "NA";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegacyFunctionCode")]
        public LegacyFunctionCodeType[] LegacyFunctionCode {
            get {
                return this.legacyFunctionCodeField;
            }
            set {
                this.legacyFunctionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string EntityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string EntityTypeID {
            get {
                return this.entityTypeIDField;
            }
            set {
                this.entityTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string EntitySubTypeID {
            get {
                return this.entitySubTypeIDField;
            }
            set {
                this.entitySubTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string ModifierOneID {
            get {
                return this.modifierOneIDField;
            }
            set {
                this.modifierOneIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string ModifierTwoID {
            get {
                return this.modifierTwoIDField;
            }
            set {
                this.modifierTwoIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://disa.mil/JointMilSyML.xsd", IsNullable=false)]
    public partial class Library {
        
        private LibraryAmplifier[] amplifiersField;
        
        private LibraryVersion[] versionsField;
        
        private LibraryContext[] contextsField;
        
        private LibraryStandardIdentity[] standardIdentitiesField;
        
        private LibraryDimension[] dimensionsField;
        
        private LibraryAffiliation[] affiliationsField;
        
        private LibraryStatus[] statusesField;
        
        private LibraryHQTFDummy[] hQTFDummiesField;
        
        private LibraryAmplifierGroup[] amplifierGroupsField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Amplifier", IsNullable=false)]
        public LibraryAmplifier[] Amplifiers {
            get {
                return this.amplifiersField;
            }
            set {
                this.amplifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Version", IsNullable=false)]
        public LibraryVersion[] Versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Context", IsNullable=false)]
        public LibraryContext[] Contexts {
            get {
                return this.contextsField;
            }
            set {
                this.contextsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StandardIdentity", IsNullable=false)]
        public LibraryStandardIdentity[] StandardIdentities {
            get {
                return this.standardIdentitiesField;
            }
            set {
                this.standardIdentitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Dimension", IsNullable=false)]
        public LibraryDimension[] Dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Affiliation", IsNullable=false)]
        public LibraryAffiliation[] Affiliations {
            get {
                return this.affiliationsField;
            }
            set {
                this.affiliationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Status", IsNullable=false)]
        public LibraryStatus[] Statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HQTFDummy", IsNullable=false)]
        public LibraryHQTFDummy[] HQTFDummies {
            get {
                return this.hQTFDummiesField;
            }
            set {
                this.hQTFDummiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AmplifierGroup", IsNullable=false)]
        public LibraryAmplifierGroup[] AmplifierGroups {
            get {
                return this.amplifierGroupsField;
            }
            set {
                this.amplifierGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryAmplifier {
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private AmplifierType typeField;
        
        private int lengthField;
        
        private string noteField;
        
        public LibraryAmplifier() {
            this.typeField = AmplifierType.TEXT;
            this.lengthField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(AmplifierType.TEXT)]
        public AmplifierType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public enum AmplifierType {
        
        /// <remarks/>
        GRAPHIC,
        
        /// <remarks/>
        TEXT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryVersion {
        
        private DoubleDigitType versionCodeField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public DoubleDigitType VersionCode {
            get {
                return this.versionCodeField;
            }
            set {
                this.versionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryContext {
        
        private ushort contextCodeField;
        
        private LibraryContextContextAmplifier[] contextAmplifiersField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public ushort ContextCode {
            get {
                return this.contextCodeField;
            }
            set {
                this.contextCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ContextAmplifier", IsNullable=false)]
        public LibraryContextContextAmplifier[] ContextAmplifiers {
            get {
                return this.contextAmplifiersField;
            }
            set {
                this.contextAmplifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryContextContextAmplifier {
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private ShapeType shapeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ShapeType Shape {
            get {
                return this.shapeField;
            }
            set {
                this.shapeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public enum ShapeType {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        CIRCLE,
        
        /// <remarks/>
        CLOVER,
        
        /// <remarks/>
        CURVE,
        
        /// <remarks/>
        DIAMOND,
        
        /// <remarks/>
        RECTANGLE,
        
        /// <remarks/>
        SQUARE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryStandardIdentity {
        
        private ushort standardIdentityCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public ushort StandardIdentityCode {
            get {
                return this.standardIdentityCodeField;
            }
            set {
                this.standardIdentityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryDimension {
        
        private LegacyLetterCodeType[] legacyDimensionCodeField;
        
        private LibraryDimensionField[] fieldsField;
        
        private LibraryDimensionSymbolSetRef[] symbolSetsField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegacyDimensionCode")]
        public LegacyLetterCodeType[] LegacyDimensionCode {
            get {
                return this.legacyDimensionCodeField;
            }
            set {
                this.legacyDimensionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public LibraryDimensionField[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SymbolSetRef", IsNullable=false)]
        public LibraryDimensionSymbolSetRef[] SymbolSets {
            get {
                return this.symbolSetsField;
            }
            set {
                this.symbolSetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryDimensionField {
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string amplifierIDField;
        
        private int xField;
        
        private int yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string AmplifierID {
            get {
                return this.amplifierIDField;
            }
            set {
                this.amplifierIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryDimensionSymbolSetRef {
        
        private DoubleDigitType symbolSetCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string instanceField;
        
        /// <remarks/>
        public DoubleDigitType SymbolSetCode {
            get {
                return this.symbolSetCodeField;
            }
            set {
                this.symbolSetCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryAffiliation {
        
        private LegacyLetterCodeType[] legacyStandardIdentityCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string contextIDField;
        
        private string standardIdentityIDField;
        
        private string dimensionIDField;
        
        private ShapeType shapeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegacyStandardIdentityCode")]
        public LegacyLetterCodeType[] LegacyStandardIdentityCode {
            get {
                return this.legacyStandardIdentityCodeField;
            }
            set {
                this.legacyStandardIdentityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string ContextID {
            get {
                return this.contextIDField;
            }
            set {
                this.contextIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string StandardIdentityID {
            get {
                return this.standardIdentityIDField;
            }
            set {
                this.standardIdentityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string DimensionID {
            get {
                return this.dimensionIDField;
            }
            set {
                this.dimensionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ShapeType Shape {
            get {
                return this.shapeField;
            }
            set {
                this.shapeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryStatus {
        
        private ushort statusCodeField;
        
        private LegacyLetterCodeType[] legacyStatusCodeField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public ushort StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegacyStatusCode")]
        public LegacyLetterCodeType[] LegacyStatusCode {
            get {
                return this.legacyStatusCodeField;
            }
            set {
                this.legacyStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryHQTFDummy {
        
        private ushort hQTFDummyCodeField;
        
        private LegacyLetterCodeType[] legacyHQTFDummyCodeField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public ushort HQTFDummyCode {
            get {
                return this.hQTFDummyCodeField;
            }
            set {
                this.hQTFDummyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegacyHQTFDummyCode")]
        public LegacyLetterCodeType[] LegacyHQTFDummyCode {
            get {
                return this.legacyHQTFDummyCodeField;
            }
            set {
                this.legacyHQTFDummyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CircleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CurveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DiamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string RectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string SquareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryAmplifierGroup {
        
        private ushort amplifierGroupCodeField;
        
        private LegacyLetterCodeType[] legacyModifierCodeField;
        
        private LibraryAmplifierGroupAmplifier[] amplifiersField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string compatibleSymbolSetIDsField;
        
        /// <remarks/>
        public ushort AmplifierGroupCode {
            get {
                return this.amplifierGroupCodeField;
            }
            set {
                this.amplifierGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegacyModifierCode")]
        public LegacyLetterCodeType[] LegacyModifierCode {
            get {
                return this.legacyModifierCodeField;
            }
            set {
                this.legacyModifierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Amplifier", IsNullable=false)]
        public LibraryAmplifierGroupAmplifier[] Amplifiers {
            get {
                return this.amplifiersField;
            }
            set {
                this.amplifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string CompatibleSymbolSetIDs {
            get {
                return this.compatibleSymbolSetIDsField;
            }
            set {
                this.compatibleSymbolSetIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class LibraryAmplifierGroupAmplifier {
        
        private ushort amplifierCodeField;
        
        private LegacyLetterCodeType[] legacyModifierCodeField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public ushort AmplifierCode {
            get {
                return this.amplifierCodeField;
            }
            set {
                this.amplifierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegacyModifierCode")]
        public LegacyLetterCodeType[] LegacyModifierCode {
            get {
                return this.legacyModifierCodeField;
            }
            set {
                this.legacyModifierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CircleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string CurveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DiamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string RectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string SquareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
}
