//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace JointMilitarySymbologyLibrary {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://disa.mil/JointMilSyML.xsd", IsNullable=false)]
    public partial class symbolSet {
        
        private doubleDigitType symbolSetCodeField;
        
        private legacyLetterCodeType[] legacyCodingSchemeCodeField;
        
        private symbolSetEntity[] entitiesField;
        
        private modifiersTypeModifier[] sectorOneModifiersField;
        
        private modifiersTypeModifier[] sectorTwoModifiersField;
        
        private symbolSetLegacySymbol[] legacySymbolsField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string dimensionIDField;
        
        /// <remarks/>
        public doubleDigitType symbolSetCode {
            get {
                return this.symbolSetCodeField;
            }
            set {
                this.symbolSetCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legacyCodingSchemeCode")]
        public legacyLetterCodeType[] legacyCodingSchemeCode {
            get {
                return this.legacyCodingSchemeCodeField;
            }
            set {
                this.legacyCodingSchemeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entity", IsNullable=false)]
        public symbolSetEntity[] entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("modifier", IsNullable=false)]
        public modifiersTypeModifier[] sectorOneModifiers {
            get {
                return this.sectorOneModifiersField;
            }
            set {
                this.sectorOneModifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("modifier", IsNullable=false)]
        public modifiersTypeModifier[] sectorTwoModifiers {
            get {
                return this.sectorTwoModifiersField;
            }
            set {
                this.sectorTwoModifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("legacySymbol", IsNullable=false)]
        public symbolSetLegacySymbol[] legacySymbols {
            get {
                return this.legacySymbolsField;
            }
            set {
                this.legacySymbolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string dimensionID {
            get {
                return this.dimensionIDField;
            }
            set {
                this.dimensionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class doubleDigitType {
        
        private ushort digitOneField;
        
        private ushort digitTwoField;
        
        private string[] textField;
        
        public doubleDigitType() {
            this.digitOneField = ((ushort)(0));
            this.digitTwoField = ((ushort)(0));
        }
        
        /// <remarks/>
        public ushort digitOne {
            get {
                return this.digitOneField;
            }
            set {
                this.digitOneField = value;
            }
        }
        
        /// <remarks/>
        public ushort digitTwo {
            get {
                return this.digitTwoField;
            }
            set {
                this.digitTwoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class legacyFunctionCodeType {
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class legacyLetterCodeType {
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class symbolSetEntity {
        
        private doubleDigitType entityCodeField;
        
        private symbolSetEntityEntityType[] entityTypesField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public doubleDigitType entityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entityType", IsNullable=false)]
        public symbolSetEntityEntityType[] entityTypes {
            get {
                return this.entityTypesField;
            }
            set {
                this.entityTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string circleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string cloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string curveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string diamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string rectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string squareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class symbolSetEntityEntityType {
        
        private doubleDigitType entityTypeCodeField;
        
        private symbolSetEntityEntityTypeEntitySubType[] entitySubTypesField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public doubleDigitType entityTypeCode {
            get {
                return this.entityTypeCodeField;
            }
            set {
                this.entityTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entitySubType", IsNullable=false)]
        public symbolSetEntityEntityTypeEntitySubType[] entitySubTypes {
            get {
                return this.entitySubTypesField;
            }
            set {
                this.entitySubTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string circleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string cloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string curveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string diamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string rectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string squareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class symbolSetEntityEntityTypeEntitySubType {
        
        private doubleDigitType entitySubTypeCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public doubleDigitType entitySubTypeCode {
            get {
                return this.entitySubTypeCodeField;
            }
            set {
                this.entitySubTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string circleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string cloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string curveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string diamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string rectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string squareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class modifiersTypeModifier {
        
        private doubleDigitType modifierCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string categoryField;
        
        private string limitUseToField;
        
        /// <remarks/>
        public doubleDigitType modifierCode {
            get {
                return this.modifierCodeField;
            }
            set {
                this.modifierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string limitUseTo {
            get {
                return this.limitUseToField;
            }
            set {
                this.limitUseToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class symbolSetLegacySymbol {
        
        private legacyFunctionCodeType[] legacyFunctionCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string entityIDField;
        
        private string entityTypeIDField;
        
        private string entitySubTypeIDField;
        
        private string modifierOneIDField;
        
        private string modifierTwoIDField;
        
        public symbolSetLegacySymbol() {
            this.entityIDField = "NA";
            this.entityTypeIDField = "NA";
            this.entitySubTypeIDField = "NA";
            this.modifierOneIDField = "NA";
            this.modifierTwoIDField = "NA";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legacyFunctionCode")]
        public legacyFunctionCodeType[] legacyFunctionCode {
            get {
                return this.legacyFunctionCodeField;
            }
            set {
                this.legacyFunctionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string entityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string entityTypeID {
            get {
                return this.entityTypeIDField;
            }
            set {
                this.entityTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string entitySubTypeID {
            get {
                return this.entitySubTypeIDField;
            }
            set {
                this.entitySubTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string modifierOneID {
            get {
                return this.modifierOneIDField;
            }
            set {
                this.modifierOneIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        [System.ComponentModel.DefaultValueAttribute("NA")]
        public string modifierTwoID {
            get {
                return this.modifierTwoIDField;
            }
            set {
                this.modifierTwoIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://disa.mil/JointMilSyML.xsd", IsNullable=false)]
    public partial class library {
        
        private libraryVersion[] versionsField;
        
        private libraryContext[] contextsField;
        
        private libraryStandardIdentity[] standardIdentitiesField;
        
        private libraryDimension[] dimensionsField;
        
        private libraryAffiliation[] affiliationsField;
        
        private libraryStatus[] statusesField;
        
        private libraryHqTFDummy[] hqTFDummiesField;
        
        private libraryAmplifierGroup[] amplifierGroupsField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("version", IsNullable=false)]
        public libraryVersion[] versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("context", IsNullable=false)]
        public libraryContext[] contexts {
            get {
                return this.contextsField;
            }
            set {
                this.contextsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("standardIdentity", IsNullable=false)]
        public libraryStandardIdentity[] standardIdentities {
            get {
                return this.standardIdentitiesField;
            }
            set {
                this.standardIdentitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dimension", IsNullable=false)]
        public libraryDimension[] dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("affiliation", IsNullable=false)]
        public libraryAffiliation[] affiliations {
            get {
                return this.affiliationsField;
            }
            set {
                this.affiliationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("status", IsNullable=false)]
        public libraryStatus[] statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("hqTFDummy", IsNullable=false)]
        public libraryHqTFDummy[] hqTFDummies {
            get {
                return this.hqTFDummiesField;
            }
            set {
                this.hqTFDummiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("amplifierGroup", IsNullable=false)]
        public libraryAmplifierGroup[] amplifierGroups {
            get {
                return this.amplifierGroupsField;
            }
            set {
                this.amplifierGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryVersion {
        
        private doubleDigitType versionCodeField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public doubleDigitType versionCode {
            get {
                return this.versionCodeField;
            }
            set {
                this.versionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryContext {
        
        private ushort contextCodeField;
        
        private libraryContextContextAmplifier[] contextAmplifiersField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public ushort contextCode {
            get {
                return this.contextCodeField;
            }
            set {
                this.contextCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contextAmplifier", IsNullable=false)]
        public libraryContextContextAmplifier[] contextAmplifiers {
            get {
                return this.contextAmplifiersField;
            }
            set {
                this.contextAmplifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryContextContextAmplifier {
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private shapeType shapeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public shapeType shape {
            get {
                return this.shapeField;
            }
            set {
                this.shapeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://disa.mil/JointMilSyML.xsd")]
    public enum shapeType {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        CIRCLE,
        
        /// <remarks/>
        CLOVER,
        
        /// <remarks/>
        CURVE,
        
        /// <remarks/>
        DIAMOND,
        
        /// <remarks/>
        RECTANGLE,
        
        /// <remarks/>
        SQUARE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryStandardIdentity {
        
        private ushort standardIdentityCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public ushort standardIdentityCode {
            get {
                return this.standardIdentityCodeField;
            }
            set {
                this.standardIdentityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryDimension {
        
        private legacyLetterCodeType[] legacyDimensionCodeField;
        
        private libraryDimensionSymbolSetRef[] symbolSetsField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legacyDimensionCode")]
        public legacyLetterCodeType[] legacyDimensionCode {
            get {
                return this.legacyDimensionCodeField;
            }
            set {
                this.legacyDimensionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("symbolSetRef", IsNullable=false)]
        public libraryDimensionSymbolSetRef[] symbolSets {
            get {
                return this.symbolSetsField;
            }
            set {
                this.symbolSetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryDimensionSymbolSetRef {
        
        private doubleDigitType symbolSetCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string instanceField;
        
        /// <remarks/>
        public doubleDigitType symbolSetCode {
            get {
                return this.symbolSetCodeField;
            }
            set {
                this.symbolSetCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryAffiliation {
        
        private legacyLetterCodeType[] legacyStandardIdentityCodeField;
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string contextIDField;
        
        private string standardIdentityIDField;
        
        private string dimensionIDField;
        
        private shapeType shapeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legacyStandardIdentityCode")]
        public legacyLetterCodeType[] legacyStandardIdentityCode {
            get {
                return this.legacyStandardIdentityCodeField;
            }
            set {
                this.legacyStandardIdentityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string contextID {
            get {
                return this.contextIDField;
            }
            set {
                this.contextIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string standardIdentityID {
            get {
                return this.standardIdentityIDField;
            }
            set {
                this.standardIdentityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string dimensionID {
            get {
                return this.dimensionIDField;
            }
            set {
                this.dimensionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public shapeType shape {
            get {
                return this.shapeField;
            }
            set {
                this.shapeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryStatus {
        
        private ushort statusCodeField;
        
        private legacyLetterCodeType[] legacyStatusCodeField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        /// <remarks/>
        public ushort statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legacyStatusCode")]
        public legacyLetterCodeType[] legacyStatusCode {
            get {
                return this.legacyStatusCodeField;
            }
            set {
                this.legacyStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryHqTFDummy {
        
        private ushort hqTFDummyCodeField;
        
        private legacyLetterCodeType[] legacyHQTFDummyCodeField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public ushort hqTFDummyCode {
            get {
                return this.hqTFDummyCodeField;
            }
            set {
                this.hqTFDummyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legacyHQTFDummyCode")]
        public legacyLetterCodeType[] legacyHQTFDummyCode {
            get {
                return this.legacyHQTFDummyCodeField;
            }
            set {
                this.legacyHQTFDummyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string circleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string cloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string curveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string diamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string rectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string squareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryAmplifierGroup {
        
        private ushort amplifierGroupCodeField;
        
        private legacyLetterCodeType[] legacyModifierCodeField;
        
        private libraryAmplifierGroupAmplifier[] amplifiersField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string compatibleSymbolSetsField;
        
        /// <remarks/>
        public ushort amplifierGroupCode {
            get {
                return this.amplifierGroupCodeField;
            }
            set {
                this.amplifierGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legacyModifierCode")]
        public legacyLetterCodeType[] legacyModifierCode {
            get {
                return this.legacyModifierCodeField;
            }
            set {
                this.legacyModifierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("amplifier", IsNullable=false)]
        public libraryAmplifierGroupAmplifier[] amplifiers {
            get {
                return this.amplifiersField;
            }
            set {
                this.amplifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string compatibleSymbolSets {
            get {
                return this.compatibleSymbolSetsField;
            }
            set {
                this.compatibleSymbolSetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://disa.mil/JointMilSyML.xsd")]
    public partial class libraryAmplifierGroupAmplifier {
        
        private ushort amplifierCodeField;
        
        private legacyLetterCodeType[] legacyModifierCodeField;
        
        private string nameField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string remarksField;
        
        private string graphicField;
        
        private string circleGraphicField;
        
        private string cloverGraphicField;
        
        private string curveGraphicField;
        
        private string diamondGraphicField;
        
        private string rectangleGraphicField;
        
        private string squareGraphicField;
        
        /// <remarks/>
        public ushort amplifierCode {
            get {
                return this.amplifierCodeField;
            }
            set {
                this.amplifierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legacyModifierCode")]
        public legacyLetterCodeType[] legacyModifierCode {
            get {
                return this.legacyModifierCodeField;
            }
            set {
                this.legacyModifierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string graphic {
            get {
                return this.graphicField;
            }
            set {
                this.graphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string circleGraphic {
            get {
                return this.circleGraphicField;
            }
            set {
                this.circleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string cloverGraphic {
            get {
                return this.cloverGraphicField;
            }
            set {
                this.cloverGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string curveGraphic {
            get {
                return this.curveGraphicField;
            }
            set {
                this.curveGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string diamondGraphic {
            get {
                return this.diamondGraphicField;
            }
            set {
                this.diamondGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string rectangleGraphic {
            get {
                return this.rectangleGraphicField;
            }
            set {
                this.rectangleGraphicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string squareGraphic {
            get {
                return this.squareGraphicField;
            }
            set {
                this.squareGraphicField = value;
            }
        }
    }
}
