//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace JointMilitarySymbologyLibrary {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esri.com/jmsmlConfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://esri.com/jmsmlConfig.xsd", IsNullable=false)]
    public partial class JMSMLConfig {
        
        private JMSMLConfigETLConfig eTLConfigField;
        
        private string libraryPathField;
        
        private string libraryNameField;
        
        /// <remarks/>
        public JMSMLConfigETLConfig ETLConfig {
            get {
                return this.eTLConfigField;
            }
            set {
                this.eTLConfigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string LibraryPath {
            get {
                return this.libraryPathField;
            }
            set {
                this.libraryPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string LibraryName {
            get {
                return this.libraryNameField;
            }
            set {
                this.libraryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esri.com/jmsmlConfig.xsd")]
    public partial class JMSMLConfigETLConfig {
        
        private GraphicFolderType[] graphicFolderField;
        
        private JMSMLConfigETLConfigExportTag[] exportTagsField;
        
        private JMSMLConfigETLConfigAmplifierValue[] amplifierValuesField;
        
        private JMSMLConfigETLConfigSchemaType[] schemaTypesField;
        
        private JMSMLConfigETLConfigSchema[] schemasField;
        
        private string domainSeparatorField;
        
        private int pointSizeField;
        
        private string sVGHomeField;
        
        private string graphicHomeField;
        
        private string graphicRootField;
        
        private string graphicExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GraphicFolder")]
        public GraphicFolderType[] GraphicFolder {
            get {
                return this.graphicFolderField;
            }
            set {
                this.graphicFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExportTag", IsNullable=false)]
        public JMSMLConfigETLConfigExportTag[] ExportTags {
            get {
                return this.exportTagsField;
            }
            set {
                this.exportTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AmplifierValue", IsNullable=false)]
        public JMSMLConfigETLConfigAmplifierValue[] AmplifierValues {
            get {
                return this.amplifierValuesField;
            }
            set {
                this.amplifierValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SchemaType", IsNullable=false)]
        public JMSMLConfigETLConfigSchemaType[] SchemaTypes {
            get {
                return this.schemaTypesField;
            }
            set {
                this.schemaTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Schema", IsNullable=false)]
        public JMSMLConfigETLConfigSchema[] Schemas {
            get {
                return this.schemasField;
            }
            set {
                this.schemasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DomainSeparator {
            get {
                return this.domainSeparatorField;
            }
            set {
                this.domainSeparatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PointSize {
            get {
                return this.pointSizeField;
            }
            set {
                this.pointSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string SVGHome {
            get {
                return this.sVGHomeField;
            }
            set {
                this.sVGHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string GraphicHome {
            get {
                return this.graphicHomeField;
            }
            set {
                this.graphicHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string GraphicRoot {
            get {
                return this.graphicRootField;
            }
            set {
                this.graphicRootField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string GraphicExtension {
            get {
                return this.graphicExtensionField;
            }
            set {
                this.graphicExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esri.com/jmsmlConfig.xsd")]
    public partial class GraphicFolderType {
        
        private GraphicFolderType[] graphicFolderField;
        
        private string nameField;
        
        private string framesField;
        
        private bool echelonsField;
        
        private bool mobilitiesField;
        
        private bool hQTFFDField;
        
        private bool auxiliaryEquipmentField;
        
        private bool specialsField;
        
        private string entitiesField;
        
        private string modifierOnesField;
        
        private string modifierTwosField;
        
        private bool oCAField;
        
        public GraphicFolderType() {
            this.framesField = "false";
            this.echelonsField = false;
            this.mobilitiesField = false;
            this.hQTFFDField = false;
            this.auxiliaryEquipmentField = false;
            this.specialsField = false;
            this.oCAField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GraphicFolder")]
        public GraphicFolderType[] GraphicFolder {
            get {
                return this.graphicFolderField;
            }
            set {
                this.graphicFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        [System.ComponentModel.DefaultValueAttribute("false")]
        public string Frames {
            get {
                return this.framesField;
            }
            set {
                this.framesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Echelons {
            get {
                return this.echelonsField;
            }
            set {
                this.echelonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Mobilities {
            get {
                return this.mobilitiesField;
            }
            set {
                this.mobilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool HQTFFD {
            get {
                return this.hQTFFDField;
            }
            set {
                this.hQTFFDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AuxiliaryEquipment {
            get {
                return this.auxiliaryEquipmentField;
            }
            set {
                this.auxiliaryEquipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Specials {
            get {
                return this.specialsField;
            }
            set {
                this.specialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string Entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string ModifierOnes {
            get {
                return this.modifierOnesField;
            }
            set {
                this.modifierOnesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string ModifierTwos {
            get {
                return this.modifierTwosField;
            }
            set {
                this.modifierTwosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OCA {
            get {
                return this.oCAField;
            }
            set {
                this.oCAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esri.com/jmsmlConfig.xsd")]
    public partial class FieldType {
        
        private string idField;
        
        private string aliasField;
        
        private FieldTypeEnum typeField;
        
        private string lengthField;
        
        private string defaultField;
        
        private bool isNullableField;
        
        private string domainField;
        
        private string orderField;
        
        private string notesField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FieldTypeEnum Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsNullable {
            get {
                return this.isNullableField;
            }
            set {
                this.isNullableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esri.com/jmsmlConfig.xsd")]
    public enum FieldTypeEnum {
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        SmallInteger,
        
        /// <remarks/>
        String,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esri.com/jmsmlConfig.xsd")]
    public partial class JMSMLConfigETLConfigExportTag {
        
        private string nameField;
        
        private string descriptionField;
        
        private string valueField;
        
        public JMSMLConfigETLConfigExportTag() {
            this.descriptionField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esri.com/jmsmlConfig.xsd")]
    public partial class JMSMLConfigETLConfigAmplifierValue {
        
        private string idField;
        
        private string labelField;
        
        private string descriptionField;
        
        private string valueField;
        
        public JMSMLConfigETLConfigAmplifierValue() {
            this.descriptionField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esri.com/jmsmlConfig.xsd")]
    public partial class JMSMLConfigETLConfigSchemaType {
        
        private FieldType[] fieldsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public FieldType[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esri.com/jmsmlConfig.xsd")]
    public partial class JMSMLConfigETLConfigSchema {
        
        private FieldType[] fieldsField;
        
        private string idField;
        
        private string schemaTypeIDsField;
        
        private string symbolSetIDsField;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public FieldType[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string SchemaTypeIDs {
            get {
                return this.schemaTypeIDsField;
            }
            set {
                this.schemaTypeIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
        public string SymbolSetIDs {
            get {
                return this.symbolSetIDsField;
            }
            set {
                this.symbolSetIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
}
